FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY . .

ARG DATABASE_URL
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD

ENV DATABASE_URL=$DATABASE_URL
ENV DATABASE_USERNAME=$DATABASE_USERNAME
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD

RUN chmod +x gradlew

ENTRYPOINT ["./gradlew", "bootRun"]